<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class PelaporanTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pelaporan')->insert([
            [
                'id' => 1,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 1,
                'divisi_id' => 1,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 2,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 2,
                'divisi_id' => 2,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 3,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 4,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 1,
                'divisi_id' => 1,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 5,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 2,
                'divisi_id' => 2,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 6,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 7,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 1,
                'divisi_id' => 1,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 8,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 2,
                'divisi_id' => 2,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 9,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 10,
                'user_id' => 2,
                'kategory_id' => 1,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Iphone 11',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Ada gantungan tali',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 11,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 1,
                'divisi_id' => 1,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 12,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 2,
                'divisi_id' => 2,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 13,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 14,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 1,
                'divisi_id' => 1,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 15,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 2,
                'divisi_id' => 2,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 16,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 17,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 1,
                'divisi_id' => 1,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 18,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 2,
                'divisi_id' => 2,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 19,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 20,
                'user_id' => 2,
                'kategory_id' => 2,
                'lokasi_id' => 3,
                'divisi_id' => 3,
                'name' => 'Monitor',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Layar Kedap Kedip',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 21,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 22,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 23,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 24,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 25,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 26,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 27,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 28,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 29,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 30,
                'user_id' => 2,
                'kategory_id' => 3,
                'lokasi_id' => null,
                'divisi_id' => null,
                'name' => 'Charger',
                'slack_id' => '89DSAD7FF',
                'deskripsi' => 'Warna Putih',
                'date' => now(),
                'image_path' => '/home/jokoliber/Documents/ProjectFreelancer/web-pelaporan',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
